version: "3"

networks:

    khyber:

        external: false

        driver: bridge

volumes:

    mariadb:

        external: false

services:

    nginx:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "80:80"

        container_name: nginx

        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./steve.conf:/etc/nginx/conf.d/steve.conf"

        image: nginx:1.21.6

    mariadb:

        restart: unless-stopped

        networks:
            - khyber

        # ports:
            # - "3306:3306"

        container_name: mariadb

        volumes:
            - "mariadb:/var/lib/mysql"

        image: mariadb:10.8.3

        env_file:
            - mariadb.env

    steve:

        restart: unless-stopped

        networks:
            - khyber

        container_name: steve

        # ports:
            # - "80:80"
            # - "443:443"

        image: irasus/steve:latest

        depends_on:
            - mariadb
